In [17]:
import nixio
from os.path import join
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px

In [18]:

_nix_dir = join("/", "mnt", "c", "Users", "conta", "git", "USZ_NCH", "Human_MTL_units_scalp_EEG_and_iEEG_verbal_WM",
                "data_nix")
_file_path = join(_nix_dir, "Data_Subject_01_Session_01.h5")
nixfile = nixio.File.open(_file_path, nixio.FileMode.ReadOnly)
# nixfile.pprint()

recording_location = nixfile.sections["General"].props["Recording location"].values
recording_setup = nixfile.sections["General"].sections["Recording setup"].props["Recording setup EEG"].values

_electrode_map = nixfile.blocks[
    "Data_Subject_01_Session_01"].groups[
    "Scalp EEG electrode information"].data_arrays[
    "Scalp_Electrode_EEGLAB_BESA_Coordinates"]

# See <https://eeglab.org/tutorials/ConceptsGuide/coordinateSystem.html>
# in x, y ,z
eeg_electrode_locations = np.ndarray(_electrode_map.shape)
_electrode_map.read_direct(eeg_electrode_locations)

In [39]:
print(eeg_electrode_locations)

[[ 5.75510634e+01  4.82004273e+01  3.98697117e+01]
 [ 5.75840261e+01 -4.81425965e+01  3.98919834e+01]
 [ 3.86812534e-15  6.31712807e+01  5.68716915e+01]
 [ 3.86788221e-15 -6.31673102e+01  5.68761015e+01]
 [-5.75510634e+01  4.82004273e+01  3.98697117e+01]
 [-5.75840261e+01 -4.81425965e+01  3.98919834e+01]
 [-8.07840138e+01  2.61330144e+01 -4.00108454e+00]
 [-8.07840138e+01 -2.61330144e+01 -4.00108454e+00]
 [ 4.98713779e+01  6.84233350e+01 -7.48951836e+00]
 [ 4.99265268e+01 -6.83835903e+01 -7.48508507e+00]
 [ 5.17649254e-15  8.45385386e+01 -8.84508251e+00]
 [ 5.17649254e-15 -8.45385386e+01 -8.84508251e+00]
 [-4.98713779e+01  6.84233350e+01 -7.48951836e+00]
 [-4.99265268e+01 -6.83835903e+01 -7.48508507e+00]
 [ 6.07384809e+01 -0.00000000e+00  5.94629038e+01]
 [ 5.20474890e-15 -0.00000000e+00  8.50000000e+01]
 [-6.07384809e+01 -7.43831863e-15  5.94629038e+01]
 [ 3.68031324e-15  6.01040764e+01 -6.01040764e+01]
 [ 3.68031324e-15 -6.01040764e+01 -6.01040764e+01]]


In [38]:
# BESA map: +X is nose, +Y is left, +Z is up
eeg_electrode_locations_df = pd.DataFrame(eeg_electrode_locations, columns=['X', 'Y', 'Z'])
# Sampled by hand according to <https://eeglab.org/tutorials/ConceptsGuide/coordinateSystem.html>
eeg_electrode_locations_df.insert(3, "location",
                                  ["F3", "F4", "C3", "C4", "P3", "P4", "O1", "O2", "F7", "F8", "T7", "T8", "P7", "P8",
                                   "FZ", "CZ", "PZ", "LPA",
                                   "RPA"])
print(df.to_string())
fig = px.scatter_3d(eeg_electrode_locations_df, x='X', y='Y', z='Z', color=df.index)
fig.show()